version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vilokanam
      POSTGRES_USER: vilokanam
      POSTGRES_PASSWORD: vilokanam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vilokanam-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - vilokanam-network

  # Blockchain node
  blockchain:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9944:9944"
      - "9615:9615"
    networks:
      - vilokanam-network

  # Signaling server for WebRTC
  signaling:
    build:
      context: ./signaling-server
    ports:
      - "8080:8080"
    networks:
      - vilokanam-network
    volumes:
      - ./signaling-server:/app
      - /app/node_modules

  # API server
  api:
    build:
      context: ./backend/api
    ports:
      - "3001:3001"
    networks:
      - vilokanam-network
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/api:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  vilokanam-network:
    driver: bridge